- Network:
    - AdGuard:
        icon: adguard-home.png
        href: http://192.168.1.194
        description: DNS Filtering
        widget:
          type: adguard
          url: http://192.168.1.194
          username: {{HOMEPAGE_VAR_ADGUARD_USERNAME}}
          password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}
    - Gluetun:
        icon: gluetun.png
        href: http://192.168.1.194:8000
        description: VPN Status
        widget:
          type: gluetun
          url: http://192.168.1.194:8000
    - Speedtest:
        icon: speedtest-tracker.png
        href: http://192.168.1.194:8765
        description: Connection Speed
        widget:
          type: speedtest
          url: http://192.168.1.194:8765

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.1.194:8096
        description: Media Server
        widget:
          type: jellyfin
          url: http://192.168.1.194:8096
          key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
          enableBlocks: true
          enableNowPlaying: false
    - qBittorrent:
        icon: qbittorrent.png
        href: http://192.168.1.194:8080
        description: Torrent Client
        widget:
          type: qbittorrent
          url: http://gluetun:8080
          username: "{{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}"
          password: "{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}"

- Management:
    - Sonarr:
        icon: sonarr.png
        href: http://192.168.1.194:8989
        description: TV Shows
        widget:
          type: sonarr
          url: http://192.168.1.194:8989
          key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
    - Radarr:
        icon: radarr.png
        href: http://192.168.1.194:7878
        description: Movies
        widget:
          type: radarr
          url: http://192.168.1.194:7878
          key: {{HOMEPAGE_VAR_RADARR_API_KEY}}
    - Prowlarr:
        icon: prowlarr.png
        href: http://192.168.1.194:9696
        description: Indexers
#        widget:
#          type: prowlarr
#         url: http://192.168.1.194:9696
#          key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}
    - Bazarr:
        icon: bazarr.png
        href: http://192.168.1.194:6767
        description: Subtitles
#        widget:
#          type: bazarr
#          url: http://192.168.1.194:6767
#          key: {{HOMEPAGE_VAR_BAZARR_API_KEY}}

- System:
    - Portainer:
        icon: portainer.png
        href: http://192.168.1.194:9000
        description: Container Management
        widget:
          type: portainer
          url: http://192.168.1.194:9000
          env: 3
          key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}
    - Watchtower:
        icon: watchtower.png
        href: http://192.168.1.194:8484
        description: Auto Updates
        widget:
          type: watchtower
          url: http://192.168.1.194:8484
          key: {{HOMEPAGE_VAR_WATCHTOWER_TOKEN}}
    - n8n:
        icon: n8n.png
        href: http://192.168.1.194:5678
        description: Workflow Automation
        widget:
          type: customapi
          url: http://192.168.1.194:5678/api/v1/workflows
          headers:
            X-N8N-API-KEY: "{{HOMEPAGE_VAR_X_N8N_API_KEY}}"
          mappings:
            - field: data
              label: Workflows
              format: size
- Trending:
    - 1337x:
        widget:
          type: iframe
          src: http://192.168.1.194:3002/view/1337x
          classes: h-72
    - EZTV:
        widget:
          type: iframe
          src: http://192.168.1.194:3002/view/EZTV
          classes: h-72
